### ISSUE TITLE
Failing Github workflows with error: `TypeError: can't compare offset-naive and offset-aware datetimes`

### ISSUE THREAD

**Issue by basiliskus** [flexion/devops-deployment-metrics#289]
Our weekly metric runs are failing consistently for the past few weeks with the error: `TypeError: can't compare offset-naive and offset-aware datetimes`. 

### Which operating system and Python version are you using? 
macOS Ventura 13.6.1 / python 3.9.18
### Which version of this project are you using? 
latest from main branch
### What did you do?
In our weekly scheduled run of the metrics, using github actions, the metrics workflow is failing for the past few weeks. [Here's an example](https://github.com/CDCgov/trusted-intermediary/actions/runs/6613107732/job/17960293535)
### What did you expect to see?
Expect for the run to finish successfully and generate the metrics output file
### What did you see instead?
The run fails with the following error: `TypeError: can't compare offset-naive and offset-aware datetimes`
Here's the full stacktrace:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/.cache/pypoetry/virtualenvs/devops-deployment-metrics-Ca1kua2f-py3.9/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/.cache/pypoetry/virtualenvs/devops-deployment-metrics-Ca1kua2f-py3.9/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/runner/.cache/pypoetry/virtualenvs/devops-deployment-metrics-Ca1kua2f-py3.9/lib/python3.9/site-packages/click/core.py", line 14[34](https://github.com/CDCgov/trusted-intermediary/actions/runs/6613107732/job/17960293535#step:7:35), in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/.cache/pypoetry/virtualenvs/devops-deployment-metrics-Ca1kua2f-py3.9/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/work/trusted-intermediary/trusted-intermediary/devops-deployment-metrics/src/devops_deployment_metrics/__main__.py", line 64, in main
    m.save()
  File "/home/runner/work/trusted-intermediary/trusted-intermediary/devops-deployment-metrics/src/devops_deployment_metrics/metrics.py", line [39](https://github.com/CDCgov/trusted-intermediary/actions/runs/6613107732/job/17960293535#step:7:40), in save
    results = self.calculate(deployments)
  File "/home/runner/work/trusted-intermediary/trusted-intermediary/devops-deployment-metrics/src/devops_deployment_metrics/metrics.py", line 84, in calculate
    for start_date, deployments in deployments_in_period:
  File "/home/runner/work/trusted-intermediary/trusted-intermediary/devops-deployment-metrics/src/devops_deployment_metrics/metrics.py", line 59, in get_deployments_in_period
    [
  File "/home/runner/work/trusted-intermediary/trusted-intermediary/devops-deployment-metrics/src/devops_deployment_metrics/metrics.py", line 62, in <listcomp>
    if start_date <= deployment.run_started < end_date
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by basiliskus** [comment]
I troubleshooted the issue today and found that it's caused when comparing dates with and without timezone specified. I plan to submit a fix tomorrow
